### ISSUE TITLE
Implement set_frame() function

### ISSUE THREAD

**Issue by yosefahab** [houqp/leptess#53]
I'm currently working with the [ffmpeg_the_third](https://crates.io/crates/ffmpeg-the-third) crate to extract some video frames, which are raw [u8] slices, attempting to use this with `set_image_from_mem()` and then applying ocr causes a panic: 
> Error in pixReadMem: Unknown format: no pix returned
> Please call SetImage before attempting recognition.

i was also experementing with another (less flexible) tesseract crate and found [set_frame()](https://docs.rs/tesseract/0.12.0/tesseract/struct.Tesseract.html#method.set_frame) function which seems to work fine, i'm not sure why.

Would it be possible to implement it?

**Comment by ccouzens** [comment]
Hi,

> which are raw [u8] slices

The bytes need an encoding in order to represent an image. I believe tesseract usually prefers the buffers to be tiff formatted (eg [this example](https://github.com/houqp/leptess/blob/master/examples/set_from_image_crate.rs#L19)).

`set_frame` takes additional metadata about the image which is why you can pass in a raw buffer. 

Would it be possible to dump the `[u8] slice` to a file and provide the parameters you were using with `set_frame` such that we can make it into a test case?

**Comment by yosefahab** [comment]
I've experimented a bit more into that, and found that [ffmpeg_the_third](https://crates.io/crates/ffmpeg-the-third) might have some issues with extracting frames as images, the resulting bytes aren't exactly correct, and converting them to image formats isn't exactly straightfoward (or necessarily correct).

I tried a different [ffmpeg crate](https://crates.io/crates/ffmpeg-frame-grabber) which has a built in `Frame` struct that works with the example you provided.
That being said, if you still want to implement `set_frame()` let me know and i'll provide you with data you need.

Thank you.

**Comment by ccouzens** [comment]
Great. It's good you've got it working.

I'll close this issue for now, but if there's additional demand for the feature I might ask for your help with example data.
